name: Check the quality of my code
on:
  push:

jobs:
  quality_check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run format 1
        working-directory: .\week1\CurrencyConverter\lib
        run: flutter format main.dart
      - name: Run analysis 1
        working-directory: .\week1\CurrencyConverter
        run: flutter analyze