name: Check the quality of my code
on:
  push:

jobs:
  quality_check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run format 1
        working-directory: .\week1\CurrencyConverter\lib
        run: flutter format -l 120 main.dart
      - name: Run analysis 1
        working-directory: .\week1\CurrencyConverter
        run: flutter analyze
      - name: Run format 2.1
        working-directory: .\week2\luckyNumber\lib
        run: flutter format -l 120 main.dart
      - name: Run analysis 2.1
        working-directory: .\week2\luckyNumber
        run: flutter analyze
      - name: Run format 2.2
        working-directory: .\week2\number_shape\lib
        run: flutter format -l 120 main.dart
      - name: Run analysis 2.2
        working-directory: .\week2\number_shape
        run: flutter analyze
      - name: Run format 3.1
        working-directory: .\week3\tic_tac_toe\lib
        run: flutter format -l 120 --set-exit-if-changed .
      - name: Run analysis 3.1
        working-directory: .\week3\tic_tac_toe
        run: flutter analyze