name: Check the quality of my code
on:
  push:
    paths:
      - week1\CurrencyConverter
      - week2\luckyNumber
      - week2\number_shape
jobs:
  quality_check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run format
        run: flutter format -l 120 --set-exit-if-changed
      - name: Run analysis
        run: flutter analyze